### ISSUE TITLE
How to import into my android project (Android Studio with Cmake compiler)

### ISSUE THREAD

**Issue by sleepinghorses** [bashbug/pcl-for-android#2]
Hi

Cound you add an example to import the libraries into my project please?

Thanks!

**Comment by Godric877** [comment]
Yes, It would be really helpful if you could provide instructions on how to include these in our 
Android Project

**Comment by loulansuiye** [comment]
encounter ERROR for libspc++

**Comment by bashbug** [comment]
Hi @sleepinghorses , @Godric877 and @loulansuiye I've updated the cross-compilation scripts and added an example-app how to integrate pcl into an android project.
