### ISSUE TITLE
Error when I want to compile 

### ISSUE THREAD

**Issue by CindyB33** [bashbug/pcl-for-android#3]
Hello !
I followed every steps and during the "./pcl-build-for-android.sh", the compiler tells that I have not any NDK. But when I do a echo $ANDROID_NDK or a printenv ANDROID_NDK the good path is printed.

I have the r10e Android NDK, maybe it is not compatible ?
Can someone help me ?

**Comment by bashbug** [comment]
@CindyB33 sorry for the late reply. I've updated the scripts to make it more easy to use. There is no need to set any environment variables anymore. The current cross-compilation uses android-ndk-r20. Please checkout master to give it a try!
