### ISSUE TITLE
build for other ABIs

### ISSUE THREAD

**Issue by vprodanovic** [bashbug/pcl-for-android#4]
Hi, I cannot get to build the PCL for android for an ABI different than armeabi-v7a.
I have tried to change the first line in the pcl-build-for-android.sh script to needed ABI, but no luck.. Any help?

**Comment by bashbug** [comment]
Hi @vprodanovic I have updated the cross-compilation scripts to support arm64-v8a, using ndk-r20. Please keep in mind that the cross-compilation even on 16GB RAM and 8 Cores needs around 20 min. Thanks to pcl ;)

**Comment by bashbug** [comment]
close issue because of inactivity
