### ISSUE TITLE
how to build for armeaib-v7 

### ISSUE THREAD

**Issue by luckyer** [bashbug/pcl-for-android#6]

**Comment by bashbug** [comment]
@luckyer I have added armeabi-v7a support.

**Comment by luckyer** [comment]
Hi， I've receive your message, but i still get the err:
ERROR: flann/1.9.1@bashbug/stable: Error in source() method, line 48
	git.clone("https://github.com/mariusmuja/flann.git", self.version)
	CalledProcessError: Command 'git clone "https://github.com/mariusmuja/flann.git" . --branch 1.9.1 ' returned non-zero exit status 128
I am not familiar with python, and i failed to find a way to solve this , so here again ask for your help.

**Comment by bashbug** [comment]
Hi @luckyer! Seems that you have problems to call on your machine a normal git command:
`git clone "https://github.com/mariusmuja/flann.git" . --branch 1.9.1`
You can try to call this command directly to get maybe a better error message.

**Comment by bashbug** [comment]
close issue because of inactivity
