### ISSUE TITLE
undefined reference to `pcl::KdTreeFLANN<pcl::InterestPoint, flann::L2_Simple<float> >::KdTreeFLANN(bool)

### ISSUE THREAD

**Issue by jameshardennnnn** [bashbug/pcl-for-android#8]
Hi,
   I add pcl removing outliers such as StatisticalOutlierRemoval filter in native-lib.cpp using example-app project with its default CMakeLists.
  When building the project using Android Studio, it always throws errors like:
/opt/conan/data/pcl/1.9.1/bashbug/stable/build/1dbc8a6a865a8fad699417711b0b0b490d4d2d18/pcl/search/include/pcl/search/impl/kdtree.hpp:48: undefined reference to `pcl::KdTreeFLANN<pcl::InterestPoint, flann::L2_Simple<float> >::KdTreeFLANN(bool)'
   I don't know how to sovle this, so here ask for your help.

**Comment by bashbug** [comment]
@jameshardennnnn can you please provide me a code snipped to reproduce the issue. Thanks!

**Comment by bashbug** [comment]
@jameshardennnnn please checkout latest master.
From the error log you can see, that the linker has an undefined reference to kdtree.hpp. Means you need to include that file. I guess that you tried this example http://pointclouds.org/documentation/tutorials/statistical_outlier.php which has also not all needed includes. I've updated native-lib.cpp using this example with the correct includes. I hope this helps!

**Comment by jameshardennnnn** [comment]
@bashbug I checked out the latest code, and it worked!  Thanks for your help!
I did try the example code from pcl tutorials, and it did not work. So I am confused about the difference between “#include <pcl/filters/statistical_outlier_removal.h>“ and “ #include <pcl/filters/impl/statistical_outlier_removal.hpp> “

**Comment by jameshardennnnn** [comment]
@bashbug one more question for help.
When I use  VoxelGrid filter example [http://pointclouds.org/documentation/tutorials/voxel_grid.php], it still does not work.
erros like: /opt/conan/data/pcl/1.9.1/bashbug/stable/package/1dbc8a6a865a8fad699417711b0b0b490d4d2d18/lib/libpcl_filters.a(filter.cpp.o): In function `pcl::Filter<pcl::PCLPointCloud2>::filter(pcl::PCLPointCloud2&)':
/opt/conan/data/pcl/1.9.1/bashbug/stable/build/1dbc8a6a865a8fad699417711b0b0b490d4d2d18/pcl/filters/src/filter.cpp:61: undefined reference to `pcl::copyPointCloud(pcl::PCLPointCloud2 const&, pcl::PCLPointCloud2&)'
can you help solve the problem？ I am very greatful for your help.

**Comment by yy19931029** [comment]
hello, how to make when I want to use ndk-r16 to do it?

**Comment by bashbug** [comment]
@jameshardennnnn looks like you are missing some includes again.
Already the last error you had is because of the outdated examples you try to compile. I recommend you to use https://github.com/PointCloudLibrary/pcl/tree/master/examples and create an issue there, if you have any problems. #

**Comment by tony23733** [comment]
@jameshardennnnn Hi Has your problem been solved?

@bashbug I added the following code to the ‘example-app native-lib.cpp’  to get the same error.
`
/pcl/filters/src/filter.cpp:61: error: undefined reference to 'pcl::copyPointCloud(pcl::PCLPointCloud2 const&, pcl::PCLPointCloud2&)'
`


```
#include <pcl/filters/voxel_grid.h>
...
float leaf_size = 1;
pcl::PCLPointCloud2::Ptr cloud2(new pcl::PCLPointCloud2());
pcl::PCLPointCloud2::Ptr cloud2_downsampled(new pcl::PCLPointCloud2());
pcl::VoxelGrid<pcl::PCLPointCloud2> vg;
vg.setInputCloud(cloud2);
vg.setLeafSize(leaf_size, leaf_size, leaf_size);
vg.filter(*cloud2_downsampled);
```
